version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: docker-test-db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: docker-test-db
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    depends_on:
      - db
    environment:
      PMA_HOST: db
      UPLOAD_LIMIT: 64M

  php:
    container_name: docker-test-php
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www
    depends_on:
      - db

  nginx:
    container_name: nginx_docker_symfony
    image: nginx:stable-alpine
    ports:
      - '80:80'
    volumes:
      - ./app:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db


#installer wsl2
#wsl -l -o #pour voir les distributions
#wsl --install -d Ubuntu-20.04
#si erreur update windows ou activer virtualisation BIOS ou faire installation manuelle

#ouvrir le fichier yml dans le terminal intégrer et faire la commande:
#docker-compose up -d
#-d, detach mode est pour liberer la console et que la bdd demarre en arriere plan

#ouvrir le dossier php et faire la commande
#docker-compose exec php bash
#note: le ficher app doit etre vide

#puis execute la commande pour isntaller symphony
#symfony new . --webapp

#composer create-project symfony/skeleton:"6.1.*" my_project_directory
#cd my_project_directory
#composer require webapp